# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - patientor

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://patientor.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_3c10e6d7aae14fe68b02c2b3107014ae }}
        password: ${{ secrets.AzureAppService_ContainerPassword_8a5df931de784d22b08fdd84fd7158f8 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: patientor.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_3c10e6d7aae14fe68b02c2b3107014ae }}/patientor:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'patientor'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_74b1fb2551d8438eb476fff578b93a66 }}
        images: 'patientor.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_3c10e6d7aae14fe68b02c2b3107014ae }}/patientor:${{ github.sha }}'