# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - patientor-

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://acr342154.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_51b4f1e1409a4beaa4771748d684c7d8 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_de70687ba0614911a922acafde5fb983 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: acr342154.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_51b4f1e1409a4beaa4771748d684c7d8 }}/patientor2:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'patientor-'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_592e65115bf547638a61cf7406c62105 }}
        images: 'acr342154.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_51b4f1e1409a4beaa4771748d684c7d8 }}/patientor2:${{ github.sha }}'